# Generated by Django 5.0.7 on 2024-07-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='event_type',
            field=models.CharField(choices=[('Wedding', 'WEDDING'), ('Engagement', 'ENGAGEMENT'), ('Birthday', 'BIRTHDAY'), ('Conference(Corporate meeting)', 'CONFERENCE'), ('Anniversary', 'ANNIVERSARY'), ('Other', 'OTHER')], max_length=50),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('Confirmed', 'CONFIRMED'), ('Rejected', 'REJECTED')], default='Pending', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='enquiry',
            unique_together={('email', 'event_date')},
        ),
    ]
