# Generated by Django 5.0.7 on 2024-07-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_enquiry_event_type_alter_enquiry_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(max_length=80),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
